buildscript {
    repositories {
        mavenLocal()
        flatDir {
            dirs 'libs'
        }
        maven {
            name = "ForgeGradle"
            url = "https://files.minecraftforge.net/maven"
        }
        maven {
            name = "gradle-plugin"
            url = "https://maven.aliyun.com/repository/gradle-plugin"
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
    }
}


apply plugin: 'net.minecraftforge.gradle'
//Only edit below this line, the above code adds and enables the necessary things for Forge to be setup.


version = "1.662"
group = "net.lrsoft.mets" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "mets"

sourceCompatibility = targetCompatibility = '1.8' // Need this here so eclipse task generates correctly.
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
}

minecraft {
    mappings channel: 'snapshot', version: '20171003-1.12'
}

repositories {
    maven {
        url = "https://www.cursemaven.com"
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2864'
    compile files ("libs/industrialcraft-2-2.8.188-ex112-dev.jar")
    compile files ("libs/SlashBlade-mc1.12-r32-deobf.jar")
    implementation fg.deobf("curse.maven:tls-306385:3314856") //The Last Smith
}
